name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - python=3.8
  - cadquery=master
  - pip
  - pip:
      - plotly
      - scipy
      - numpy
      - matplotlib
      - pillow
      - plasmaboundaries
      - sympy
      - sphinx-autodoc-typehints
      - sphinxcadquery
      - defusedxml
      - jupyter-cadquery
