name: docs-environment

channels:
  - cadquery
  - conda-forge
  - defaults

dependencies:
  - cadquery=2.1
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - moab
  - pip:
    - remove_dagmc_tags
    - sympy
    - plasmaboundaries
    - sphinx-autodoc-typehints
    - sphinxcadquery
    - defusedxml
    