name: docs-environment

# channel_priority: strict
channels:
  - conda-forge
  - cadquery
  # - defaults

dependencies:
  - cadquery=2.1
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  # - moab is an optional dependancy
  # - remove_dagmc_tags is an optional dependancy
  - pip:
    - sympy
    # - plasmaboundaries
    - sphinx-autodoc-typehints
    - sphinxcadquery
    - defusedxml
    