name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - python=3.8
  - pyparsing>=2.1.9
  - cadquery=master
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - plasmaboundaries
  - pip:
      - sympy
      - sphinx-autodoc-typehints
      - sphinxcadquery
      - defusedxml
      - jupyter-cadquery
