name: docs-environment

channels:
  - conda-forge
  - cadquery

dependencies:
  - cadquery=2.1
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - moab=5.3.0
  - remove_dagmc_tags
  - pip:
    - sympy
    - plasmaboundaries
    - sphinx-autodoc-typehints
    - sphinxcadquery
    - defusedxml
    - jupyter-cadquery
    - cad_to_h5m
