[build-system]
requires = [
    "setuptools >= 65.4.1",
    "setuptools_scm[toml] >= 7.0.5",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "paramak/_version.py"

[tool.black]
line-length = 120
