# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - develop
    - main
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'CITATION.cff'
      - 'LICENSE.txt'
      - 'readthedocs.yml'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build wheel
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build
          python3 -m build .

      - name: Get wheel name
        run: |
          echo "WHEEL_NAME=$(ls -t dist/*.whl | head -n 1)" >> $GITHUB_ENV

      - name: Build and test with Docker
        run: |
          docker build -t paramak --build-arg cq_version=2.1 --build-arg wheel=$WHEEL_NAME .
          docker run --rm paramak  /bin/bash -c "bash run_tests.sh"
