# Runs on a miniconda base container, installs required software and performs
# pytests


name: CI with install
on:
  pull_request:    
    branches:
    - develop
    - main
 
jobs:  
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.9.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install requirments
        run: |
          apt-get -y update
          apt-get install -y ffmpeg libsm6 libxext6
          conda install -c conda-forge -c cadquery cadquery=2.1
          # dagmc install includes moab and make_watertight
          conda install -c conda-forge dagmc
          python setup.py install
      - name: run tests requirments
        run: |
          bash run_tests.sh
          curl -s https://codecov.io/bash
