# Builds a dockerimage and then runs tests from within the docker enviroment

name: CI with docker build
on:
  pull_request:
    branches:
    - develop
    - main
    paths:
      - "**.py"
      - "**.ipynb"
      - "**.yml"
      - "**.cfg"
      - "**.toml"
      - "**.sh"

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Docker
        run: docker build -t paramak --build-arg cq_version=2.1 .

      - name: Run unit tests
        run: docker run --rm paramak pytest ./tests

      - name: Test examples
        run: docker run --rm paramak pytest ./examples_tests
