
name: CI - Develop from base docker
on:
  pull_request:    
    branches:
    - develop
 
jobs:  
  testing:
    runs-on: ubuntu-latest
    container:
      image: continuumio/miniconda3:4.9.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: install requirments
        run: |
          apt-get -y update
          apt-get install -y ffmpeg libsm6 libxext6
          conda install -c conda-forge -c cadquery cadquery=2.1
          conda install -c conda-forge moab
          pip install pytest-cov
      - name: run tests requirments
        run: |
          bash run_tests.sh
