# This yml file will trigger a Github Action on pushes to the develop branch.
# This Action will build and upload a Docker image to Dockerhub
# https://github.com/marketplace/actions/publish-docker

name: dockerhub-publish-geometry-dependencies

on:
  push:
    branches:
      - develop
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/fusion-energy/paramak:geometry-dependencies
          build-args: |
            cq_version=2.1
            compile_cores=2
            include_neutronics=false
